### ISSUE TITLE
Determining Entity Equivalency

### ISSUE THREAD

**Issue by epeters3** [byu-dml/d3m-mtl-db-reader#1]
While the IDs for all pipeline runs are unique, and the digests for all pipelines, datasets, and problems are unique, etc., there should be a way to tell when two pipeline runs, pipelines, problems, datasets, etc. are functionally the same. What defines "functionally the same" may depend on the context of the analysis being conducted on the data.

**Comment by orionw** [comment]
There is a equals function for most of those objects - we struggled through that for a while as well in developing the experimenter.  Here is the pipeline one, for example: https://gitlab.com/datadrivendiscovery/d3m/blob/devel/d3m/metadata/pipeline.py#L195.  If you mean "close to the same but different versions, ids, etc." that problem is definitely harder.

**Comment by epeters3** [comment]
Thanks for pointing that out Orion. That's good to know they have equals functions that check content equality.

I am using my own classes to represent each of the D3M entities in this repo, specific to a data mining project I'm doing. Honestly I didn't think about using D3M's classes to represent pipeline runs in memory. That's a pretty good idea. At this point, it may not be worth it to refactor though.

As a part of this enhancement, I'm implementing equality checks at varying degrees of granularity like you mention e.g. do two runs use the same primitives, do two runs use the same sequence of primitives, do two runs use the same sequence of primitives including primitive version numbers, etc.

I hope your internship is going well!

**Comment by orionweller** [comment]
No worries, I just thought I'd mention it in case it could help.  There are definitely pros to staying away from d3m's code as well though.  

Looks like a fun project!  Good luck!

**Comment by orionw** [comment]
No worries, I just thought I'd mention it in case it could help. There are definitely pros to staying away from d3m's code as well though.

Looks like a fun project! Good luck!

**Comment by epeters3** [comment]
This has been addressed by including the abstract method `is_tantamount_to` on the `src.entities.Entity` superclass that all entities inherit from.
